In [1]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

73
0.1461191642869969


In [2]:
#creating n dimensional array with random int values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[ 8 35 99]
[[92 32  6 63]
 [94 38 61 16]
 [46 25 89 43]]
[[[88 24]
  [53 68]
  [31  2]
  [32 22]]

 [[36 60]
  [80 43]
  [54 95]
  [22 21]]

 [[92 16]
  [42 62]
  [98 81]
  [29 97]]]


In [3]:
#creating n dimensional array with random float values
print(random.rand(3))
print(random.rand(2,3))

[0.47285122 0.95130741 0.88118004]
[[0.50280681 0.84424116 0.33266985]
 [0.03675539 0.54619047 0.93479457]]


In [4]:
a=random.randint(100,size=(3,2)).ravel()
a

array([92, 92,  4, 10, 23, 55])

In [5]:
#single element will be generated
random.choice(a)

92

In [6]:
#for generating an array with given shape and elements from the given list
random.choice([1,2,3,4,5],size=(3,4))

array([[5, 3, 5, 1],
       [4, 1, 4, 2],
       [4, 2, 4, 5]])

### pandas:
1. data manipulation, analysis and cleaning
2. tabular, unlabelled 

### creating a data frame
1. using two dictionaries


In [7]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [8]:
#using single dictionary
d1={"name":["preeti","mounika","sumathi"],"add":["hyd","adb","ap"]}
df1=pd.DataFrame(d1)
df1

name  add
0   preeti  hyd
1  mounika  adb
2  sumathi   ap

In [10]:
#using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.34,43,6,87.6,12.8,9.8,77.6,12.3,99,9])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.34       a
1        2    43.00       b
2        3     6.00       c
3        4    87.60       d
4        5    12.80       e
5        6     9.80       f
6        7    77.60       g
7        8    12.30       h
8        9    99.00       i
9       10     9.00       j

###selecting data from dataframe
1. loc
2. iloc

In [11]:
df3["column2"]

0    12.34
1    43.00
2     6.00
3    87.60
4    12.80
5     9.80
6    77.60
7    12.30
8    99.00
9     9.00
Name: column2, dtype: float64

In [12]:
df3[["column2","column3"]]

column2 column3
0    12.34       a
1    43.00       b
2     6.00       c
3    87.60       d
4    12.80       e
5     9.80       f
6    77.60       g
7    12.30       h
8    99.00       i
9     9.00       j

In [13]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [14]:
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.34
1        2    43.00
2        3     6.00
3        4    87.60
4        5    12.80
5        6     9.80

In [15]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [16]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

In [17]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [19]:
df3.shape

(10, 3)

In [20]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [21]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### viewing data from data frame
1. head()
2. tail()
3. sample()

In [22]:
#first 5 rows
df3.head()

column1  column2 column3
0        1    12.34       a
1        2    43.00       b
2        3     6.00       c
3        4    87.60       d
4        5    12.80       e

In [23]:
df3.head(3)

column1  column2 column3
0        1    12.34       a
1        2    43.00       b
2        3     6.00       c

In [24]:
df3.tail()

column1  column2 column3
5        6      9.8       f
6        7     77.6       g
7        8     12.3       h
8        9     99.0       i
9       10      9.0       j

In [25]:
df3.tail(3)

column1  column2 column3
7        8     12.3       h
8        9     99.0       i
9       10      9.0       j

In [28]:
#returns random
df3.sample()

column1  column2 column3
5        6      9.8       f

In [29]:
df3.sample(2)

column1  column2 column3
5        6      9.8       f
1        2     43.0       b

In [30]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  36.944000
std     3.02765  37.084549
min     1.00000   6.000000
25%     3.25000  10.425000
50%     5.50000  12.570000
75%     7.75000  68.950000
max    10.00000  99.000000

In [32]:
#renaming columns
df3=df3.rename(columns={"column1":"First",
                        "column2":"Second",
                        "column3":"Third"})
df3

First  Second Third
0      1   12.34     a
1      2   43.00     b
2      3    6.00     c
3      4   87.60     d
4      5   12.80     e
5      6    9.80     f
6      7   77.60     g
7      8   12.30     h
8      9   99.00     i
9     10    9.00     j